# Generated by Django 4.2.1 on 2023-06-28 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lynk_up_server.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='friends',
            field=models.ManyToManyField(blank=True, to='lynk_up_server.friend'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='lynk_up_server.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
