# Generated by Django 4.2.1 on 2023-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0003_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='place holder', max_length=200),
            preserve_default=False,
        ),
    ]
