# Generated by Django 4.2.1 on 2023-05-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0004_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='lynk_up_server.user'),
            preserve_default=False,
        ),
    ]
